### ISSUE TITLE
Lebensanzeige erstellen

### ISSUE THREAD

**Issue by Valinor666** [bugfi5h/GodotWildJamX#12]
Dabei soll es 3 Grafiken geben: Volles Herz, halbes Herz und leeres Herz.
(Es müssen nicht unbedingt Herzen sein)

**Comment by Sinucubus** [comment]
Die Lebensanzeige wird als Miniglitches erstellt in 3 Formen.
Voll = happy/voller glitch
halb = halb voller glitch
leer = toter/leerer glitch
