### ISSUE TITLE
Animation des Players

### ISSUE THREAD

**Issue by Valinor666** [bugfi5h/GodotWildJamX#14]

**Comment by Sinucubus** [comment]
@Valinor666, Sollen in diesem Issue die grafischen Animationen des Player erstellt werden?

**Comment by Sinucubus** [comment]
Animationen für Player-Movement wurden bereits in Issue #16 erstellt.

**Comment by Valinor666** [comment]
Super. Ich hab heute in 865ebfa9d7bd7b58c1dda5c51a238ebeedd900b2 deine Sprites eingebaut. Jetzt muss nur noch der Angriff aus #18 eingebaut werden. :)

**Comment by Sinucubus** [comment]
Sehr nice. :D
