### ISSUE TITLE
Icon erstellen

### ISSUE THREAD

**Issue by Valinor666** [bugfi5h/GodotWildJamX#15]

**Comment by Sinucubus** [comment]
@Valinor666, Was für ein Icon soll hier genau erstellt werden bzw. für was soll es sein?

**Comment by Valinor666** [comment]
@Sinucubus Es geht um das Icon, welches in der Titelleiste vom Fenster zu sehen ist.
Momentan ist das Godotlogo drin. Musst dafür die Datei 'assets/image/icon.png' ersetzen^^

**Comment by Sinucubus** [comment]
Also wenn es noch kein Icon gibt, hätte ich da vielleicht eine Idee. :D

**Comment by Sinucubus** [comment]
Es wurde ein custom Icon erstellt, welches das Standard-Godot Icon ersetzt.
