### ISSUE TITLE
Angriffsanimation mit doppelt so langen Armen

### ISSUE THREAD

**Issue by bugfi5h** [bugfi5h/GodotWildJamX#18]
Endpunkt der Arme sollte doppelt so lang sein wie aktuell. Animationsschritte zwischen drin wären auch noch ganz nett

**Comment by Sinucubus** [comment]
@bugfi5h, Welche Grafik soll hierfür verwendet werden? Ich hatte ja mal eine entworfen für den Angriff mit einem Arm ausgestreckt und eine andere, wenn der Player getroffen wird (beide Arme ausgestreckt). Die mit den beiden ausgestreckten Armen wird wohl aktuell als Angriffs-Animation verwendet.

**Comment by bugfi5h** [comment]
Nimm die, die für den Angriff gedacht war. Hab wohl einfach die falsche genommen.

**Comment by Sinucubus** [comment]
Alles klar. Dann werde ich mich darum kümmern. 👍
